CREATE TABLE dbo.movies (
    mov_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    mov_title varchar(50) not null,
    mov_imdb_id varchar(50) null,
    mov_rate smallint null CHECK (mov_rate >= 1 AND mov_rate <= 5),
    mov_insert_date timestamp not null DEFAULT CURRENT_DATE,
    mov_modification_date timestamp not null DEFAULT CURRENT_DATE
);

CREATE INDEX mov_pk ON dbo.movies (mov_id);
CREATE INDEX mov_imdb_id ON dbo.movies (mov_imdb_id);

--TODO ADD COLUMNS DESCRIPTIONS

CREATE OR REPLACE FUNCTION trig_update_mov_modification_date()
RETURNS TRIGGER AS $$
BEGIN
   NEW.mov_modification_date = CURRENT_DATE;
   RETURN NEW;
END;
$$ language 'plpgsql';

