CREATE TABLE dbo.showings (
    sho_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sho_cin_id bigint not null,
    sho_mov_id bigint not null,
    sho_day smallint not null CHECK (sho_day >= 0 AND sho_day <= 6),
    sho_time time with time zone not null,
    sho_insert_date timestamp not null DEFAULT CURRENT_DATE,
    sho_modification_date timestamp not null DEFAULT CURRENT_DATE
);

CREATE INDEX sho_pk ON dbo.showings (sho_id);

--TODO ADD DESCRIPTIONS

CREATE OR REPLACE FUNCTION trig_update_sho_modification_date()
RETURNS TRIGGER AS $$
BEGIN
   NEW.sho_modification_date = CURRENT_DATE;
   RETURN NEW;
END;
$$ language 'plpgsql';

