CREATE TABLE dbo.cinemas (
    cin_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cin_name varchar(50) not null,
    cin_manager_id bigint not null,
    cin_insert_date timestamp not null DEFAULT CURRENT_DATE,
    cin_modification_date timestamp not null DEFAULT CURRENT_DATE
);

CREATE INDEX cin_pk ON dbo.cinemas (cin_id);

--TODO ADD COLUMNS DESCRIPTIONS

CREATE OR REPLACE FUNCTION trig_update_cin_modification_date()
RETURNS TRIGGER AS $$
BEGIN
   NEW.cin_modification_date = CURRENT_DATE;
   RETURN NEW;
END;
$$ language 'plpgsql';


