create table public.users(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar ( 50 ) not null UNIQUE,
    password varchar ( 100 ) not null,
    enabled boolean not null
);

create table public.authorities (
    username varchar ( 50 ) not null,
    authority varchar ( 50 ) not null,
    constraint fk_authorities_users foreign key(username) references public.users(username)
);

